name: demo-caller
on:

  schedule: [{ cron: '0 0 * * *' }]

  push:
    branches: [main]
    paths: [.github/workflows/demo-caller.yml]

  pull_request:
    branches: [main]
    paths: [.github/workflows/demo-caller.yml]

  workflow_dispatch:
    inputs:
      script:
        description: script to run.
        type: string
        default: "lib.doDemo(ctx)"

jobs:
  main:
    name: "${{ github.workflow }}"
    uses: ./.github/workflows/demo.yml
    with:
      script: ${{ inputs.script || 'lib.doDemo(ctx)' }}
