on:
  push: {branches: [main]}
  workflow_dispatch:

name: github-script

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: print contents of github.context for debugging.
        uses: actions/github-script@v6
        with: { script: 'console.log(context)' }

      - name: checkout the code.
        uses: actions/checkout@v2
